1) Вычислить пропущенное значение вероятности $\newline$
Формула: $\displaystyle\sum_{i} \sum_{j}  x_{ij} = 1$

In [91]:
import numpy as np
f = open('13.txt', 'r')
X = np.genfromtxt(f, delimiter=',', dtype=float, max_rows=1)
Y = np.genfromtxt(f, delimiter=',', dtype=float, max_rows=1)
table = np.genfromtxt(f, delimiter=',', dtype=float, missing_values='NULL')
f.close()
sum = np.nansum(table)
table[np.isnan(table)] = 1 - sum
print('Значения X: ', X)
print('Значения Y: ', Y)
print('Таблица вероятностей: \n',  table)
print('ПРОПУЩЕННОЕ ЗНАЧЕНИЕ: ', np.round(1 - sum, 2))

Значения X:  [-5. 15. 18. 26. 27.]
Значения Y:  [-6. -3. -2.  9.]
Таблица вероятностей: 
 [[0.01 0.09 0.07 0.05]
 [0.07 0.02 0.01 0.07]
 [0.05 0.02 0.08 0.02]
 [0.02 0.07 0.08 0.1 ]
 [0.01 0.09 0.01 0.06]]
ПРОПУЩЕННОЕ ЗНАЧЕНИЕ:  0.01


2) Найти маргинальные распределения X и Y $\newline$
$ P(x_i)=\displaystyle\sum_j P(x_i, y_j) \newline$
$ P(y_i)=\displaystyle\sum_i P(x_i, y_j)$

In [92]:
P_X = np.round(np.sum(table, axis=1), 2)
P_Y = np.round(np.sum(table, axis=0), 2)
print('Маргинальные распределения X: ', P_X)
print('Маргинальные распределения Y: ', P_Y)

Маргинальные распределения X:  [0.22 0.17 0.17 0.27 0.17]
Маргинальные распределения Y:  [0.16 0.29 0.25 0.3 ]


3) Найти математические ожидания, дисперсии и среднеквадратические отклонения X и Y$\newline$
Математическое ожидание: $E(X)=\displaystyle\sum_i x_iP(x_i)\newline$
                        $E(Y)=\displaystyle\sum_j y_iP(y_j)$$\newline$
Дисперсия:
$\newline$ $D(X)=(x_i-E(X))^2*P(x_i)$
$\newline$ $D(X)=(y_i-E(Y))^2*P(y_i)$
$\newline$Среднеквадратическое отклонение:
$\newline$$\sigma_X=\sqrt{D(X)}$
$\newline$$\sigma_Y=\sqrt{D(Y)}$

In [93]:
E_X = np.round(np.sum(X * P_X), 2)
E_Y = np.round(np.sum(Y * P_Y), 2)
D_X =  np.round(np.sum(((X - E_X) ** 2) * P_X), 4)
D_Y =  np.round(np.sum(((Y - E_Y) ** 2) * P_Y), 4)
sigma_X = np.sqrt(D_X)
sigma_Y = np.sqrt(D_Y)
print('Математическое ожидание X: ', E_X)
print('Математическое ожидание Y: ', E_Y)
print('Дисперсия X: ', D_X)
print('Дисперсия Y: ', D_Y)
print('Среднеквадратическое отклонение X: ', np.round(sigma_X, 5))
print('Среднеквадратическое отклонение Y: ', np.round(sigma_Y, 5))

Математическое ожидание X:  16.12
Математическое ожидание Y:  0.37
Дисперсия X:  145.4256
Дисперсия Y:  33.5331
Среднеквадратическое отклонение X:  12.05925
Среднеквадратическое отклонение Y:  5.79078


4) Найти ковариацию и коэффициент корреляции от  X и Y
$\newline$Ковариация:
$\newline$$Cov(X,Y)=\displaystyle\sum_{i} \sum_{j} (x_i-E(X)) * (y_j - E(Y)) * P(x_i, y_j)$
$\newline$$\rho_{XY} = \frac{Cov(X,Y)}{\sigma_X\sigma_Y} $

In [94]:
cov_XY = 0
for i in range(len(X)):
    for j in range(len(Y)):
        cov_XY += (X[i] - E_X)*(Y[j] - E_Y) * table[i][j]
p = cov_XY/(sigma_X*sigma_Y)
print('Ковариация: ', np.round(cov_XY, 5))
print('Коэффициент корреляции: ', np.round(p, 5))

Ковариация:  5.7556
Коэффициент корреляции:  0.08242


5) Проверить независимость случайных величин X и Y
$\newline$Случайные велечины X и Y независимы, если:
$\newline$$\forall i,j: $  $P(x_i, y_j)=P(x_i) * P(y_j)$ 

In [95]:
indep = True
for i in range(len(X)):
    for j in range(len(Y)):
        if P_X[i] * P_Y[j] != table[i][j]:
            indep = False
            break
if indep:
    print("Случайные величины независимы")
else:
    print("Случайные величины зависимы")

Случайные величины зависимы


6) Найти условные распределения $X$ при условии $Y=y_j$ и $Y$ при условии $X = x_i$
$\newline$ $P(x_i|y_j)=\frac{P(x_i, y_j)}{P(y_j)}$
$\newline$ $P(y_j|x_i)=\frac{P(x_i, y_j)}{P(x_i)}$

In [96]:
P_X_Y = table.copy()
P_Y_X = table.copy()
for i in range(len(X)):
    P_Y_X[i] = table[i] / P_X[i]
    for j in range(len(Y)):
        P_X_Y[i][j] = table[i][j] / P_Y[j]
print('Yсловные распределения X при условии Y=yj:\n', np.round(P_X_Y, 3))
print('Yсловные распределения Y при условии X=xi:\n', np.round(P_Y_X, 3))

Yсловные распределения X при условии Y=yj:
 [[0.063 0.31  0.28  0.167]
 [0.438 0.069 0.04  0.233]
 [0.312 0.069 0.32  0.067]
 [0.125 0.241 0.32  0.333]
 [0.062 0.31  0.04  0.2  ]]
Yсловные распределения Y при условии X=xi:
 [[0.045 0.409 0.318 0.227]
 [0.412 0.118 0.059 0.412]
 [0.294 0.118 0.471 0.118]
 [0.074 0.259 0.296 0.37 ]
 [0.059 0.529 0.059 0.353]]


7) Вычислите условные математические ожидания $X$ при условии $Y=y_j$ и $Y$ при условии $X = x_i$
$\newline$$E(X|y_j)=\displaystyle\sum_{i} x_i P(x_i|y_j)$
$\newline$$E(Y|x_i)=\displaystyle\sum_{j} y_j P(x_i|y_j)$

In [97]:
E_X_Y = [0] * len(Y)
E_Y_X = [0] * len(X)
for i in range(len(X)):
    for j in range(len(Y)):
        E_X_Y[j] += X[i] * P_X_Y[i][j]
        E_Y_X[i] += Y[j] * P_Y_X[i][j]
print('Yсловные математические ожидания  𝑋 при условии  Y=yi:', np.round(E_X_Y, 4))
print('Yсловные математические ожидания  Y при условии  X=xi:', np.round(E_Y_X, 4))

Yсловные математические ожидания  𝑋 при условии  Y=yi: [16.8125 15.3793 14.36   17.9333]
Yсловные математические ожидания  Y при условии  X=xi: [-0.0909  0.7647 -2.      1.5185  1.1176]
